server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    index index.php index.html;
    charset utf-8;

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    # Vite HMR - используем CODESNIP-PHP вместо laravel.test
    location /@vite {
        proxy_pass http://codesnip-php:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /livewire {
        try_files $uri $uri/ /index.php?$query_string;
    }

    include /etc/nginx/conf.d/zz-log-stream.inc;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM через codesnip-php
    location ~ \.php$ {
        fastcgi_pass codesnip-php:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;

        fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
        fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
        fastcgi_param HTTP_X_FORWARDED_HOST $host;
        fastcgi_param HTTP_X_FORWARDED_PORT $server_port;
        fastcgi_param PHP_IDE_CONFIG "serverName=codesnip";
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
