# docker/8.5/supervisord.conf
[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=/usr/sbin/php-fpm8.5 -F
autostart=true
autorestart=true
user=root
stdout_logfile=/var/www/html/storage/logs/php-fpm.log
stderr_logfile=/var/www/html/storage/logs/php-fpm-error.log

[program:horizon]
command=/usr/bin/php /var/www/html/artisan horizon
autostart=true
autorestart=true
user=sail
stdout_logfile=/var/www/html/storage/logs/horizon.log
stderr_logfile=/var/www/html/storage/logs/horizon-error.log
